export const ACCOUNT_SET_INFO_USER = 'ACCOUNT_SET_INFO_USER';
export const ACCOUNT_REMOVE_INFO_USER = 'ACCOUNT_REMOVE_INFO_USER';
export const ACCOUNT_SET_WORK_DEPARTMENT = 'ACCOUNT_SET_WORK_DEPARTMENT';
